export const clothesData = [
  {
    id: 1,
    name: "Sierra Structured Tee",
    rating: 4.5,
    description: "Heavyweight organic cotton with a crisp shoulder line.",
    price: "$48",
    category: "Essentials",
    badge: "Bestseller",
    colors: ["Ivory", "Charcoal", "Olive"],
    sizes: ["XS", "S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 2,
    name: "Monroe Tapered Denim",
    rating: 4.8,
    description: "Soft-stretch selvedge denim with a refined taper.",
    price: "$118",
    category: "Denim",
    badge: "New",
    colors: ["Indigo", "Jet Black"],
    sizes: ["28", "30", "32", "34"],
    image:
      "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 3,
    name: "Cloudline Oversized Hoodie",
    rating: 4.2,
    description: "Brushed fleece interior with dropped shoulder silhouette.",
    price: "$86",
    category: "Streetwear",
    badge: "Limited",
    colors: ["Sand", "Bone", "Slate"],
    sizes: ["S", "M", "L", "XL"],
    image:
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 4,
    name: "Noir Moto Jacket",
    rating: 4.9,
    description: "Supple vegan leather with polished gunmetal hardware.",
    price: "$220",
    category: "Outerwear",
    badge: "Top Rated",
    colors: ["Black"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 5,
    name: "Rosette Midi Dress",
    rating: 4.4,
    description: "Airy chiffon drape with a hand-painted floral print.",
    price: "$132",
    category: "Dresses",
    badge: "Editor Pick",
    colors: ["Rose", "Sky"],
    sizes: ["XS", "S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 6,
    name: "Transit Cargo Joggers",
    rating: 4.1,
    description: "Tapered utility pants with hidden zip pocket details.",
    price: "$94",
    category: "Athleisure",
    badge: "Popular",
    colors: ["Khaki", "Stone", "Ink"],
    sizes: ["S", "M", "L", "XL"],
    image:
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 7,
    name: "Haven Wool Overcoat",
    rating: 4.7,
    description: "Tailored longline overcoat made for layered city looks.",
    price: "$259",
    category: "Outerwear",
    badge: "Premium",
    colors: ["Camel", "Graphite"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 8,
    name: "Pulse Graphic Shirt",
    rating: 4.3,
    description: "Dense combed cotton featuring seasonal artwork print.",
    price: "$62",
    category: "Streetwear",
    badge: "Drop 03",
    colors: ["Washed Black", "Off White"],
    sizes: ["S", "M", "L", "XL"],
    image:
      "https://images.unsplash.com/photo-1484515991647-c5760fcecfc7?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 9,
    name: "Marina Linen Shirt",
    rating: 4.6,
    description: "Breathable weave with a clean resort-inspired fit.",
    price: "$89",
    category: "Shirts",
    badge: "Summer",
    colors: ["White", "Sea Blue", "Sage"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 10,
    name: "Arc High-Rise Leggings",
    rating: 4.9,
    description: "Sculpting knit with matte finish and sweat-wick comfort.",
    price: "$74",
    category: "Athleisure",
    badge: "Top Rated",
    colors: ["Ebony", "Cocoa", "Steel"],
    sizes: ["XS", "S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1506629905607-d405b7a6e716?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 11,
    name: "Ridge Trucker Jacket",
    rating: 4.5,
    description: "Classic denim shell with brushed interior lining.",
    price: "$145",
    category: "Outerwear",
    badge: "Classic",
    colors: ["Blue Wash", "Ecru"],
    sizes: ["S", "M", "L", "XL"],
    image:
      "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 12,
    name: "North Knit Turtleneck",
    rating: 4.2,
    description: "Soft rib-knit profile with warm neck wrap design.",
    price: "$98",
    category: "Knitwear",
    badge: "Cold Weather",
    colors: ["Charcoal", "Sand", "Berry"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 13,
    name: "Emerald Slip Dress",
    rating: 4.8,
    description: "Bias-cut satin slip crafted for evening elegance.",
    price: "$168",
    category: "Dresses",
    badge: "Evening",
    colors: ["Emerald", "Midnight"],
    sizes: ["XS", "S", "M"],
    image:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 14,
    name: "Nimbus Puffer Vest",
    rating: 4.0,
    description: "Light thermal insulation and water-resistant shell.",
    price: "$124",
    category: "Outerwear",
    badge: "Travel",
    colors: ["Taupe", "Black"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1616258734679-2d8f4f5bbf8f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 15,
    name: "Harbor Chino Shorts",
    rating: 4.3,
    description: "Mid-thigh modern cut with soft peached cotton feel.",
    price: "$58",
    category: "Bottoms",
    badge: "Warm Weather",
    colors: ["Khaki", "Navy", "Stone"],
    sizes: ["28", "30", "32", "34"],
    image:
      "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 16,
    name: "Canyon Flannel Shirt",
    rating: 4.6,
    description: "Brushed twill weave for cozy layering comfort.",
    price: "$76",
    category: "Shirts",
    badge: "Bestseller",
    colors: ["Rust", "Forest", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 17,
    name: "Aero Running Shorts",
    rating: 4.4,
    description: "Featherweight shell with built-in support liner.",
    price: "$52",
    category: "Athleisure",
    badge: "Training",
    colors: ["Black", "Signal Red", "Ice"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1593032465171-8bd5f5f6f7ce?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 18,
    name: "Alpine Cashmere Scarf",
    rating: 4.9,
    description: "Ultra-fine cashmere blend with luxe brushed finish.",
    price: "$92",
    category: "Accessories",
    badge: "Luxury",
    colors: ["Cream", "Camel", "Ash"],
    sizes: ["One Size"],
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 19,
    name: "Velour Night Blazer",
    rating: 4.7,
    description: "Tailored velvet blazer with satin peak lapel details.",
    price: "$189",
    category: "Occasion",
    badge: "Event Ready",
    colors: ["Wine", "Midnight"],
    sizes: ["S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 20,
    name: "Breton Stripe Longsleeve",
    rating: 4.5,
    description: "Nautical stripe classic in soft double-knit cotton.",
    price: "$64",
    category: "Essentials",
    badge: "Everyday",
    colors: ["Navy", "Cream", "Black"],
    sizes: ["XS", "S", "M", "L"],
    image:
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80",
  },
];
